<?php

namespace ContainerUiptYz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Rs4GYAyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.rs4GYAy' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/remote-event/Messenger/ConsumeRemoteEventHandler.php';

        return $container->privates['.messenger.handler_descriptor.rs4GYAy'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\RemoteEvent\Messenger\ConsumeRemoteEventHandler(($container->privates['.service_locator.Xbsa8iG'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))), []);
    }
}
