<?php

namespace ContainerUiptYz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_AwhOMiCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.awhOMiC' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Messenger/SendWebhookHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Server/TransportInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Server/Transport.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Server/RequestConfiguratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Server/HeadersConfigurator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Server/JsonBodyConfigurator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Server/HeaderSignatureConfigurator.php';

        return $container->privates['.messenger.handler_descriptor.awhOMiC'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\Webhook\Messenger\SendWebhookHandler(new \Symfony\Component\Webhook\Server\Transport(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), new \Symfony\Component\Webhook\Server\HeadersConfigurator(), new \Symfony\Component\Webhook\Server\JsonBodyConfigurator(($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container))), new \Symfony\Component\Webhook\Server\HeaderSignatureConfigurator())), []);
    }
}
