<?php

namespace ContainerUiptYz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HomeController' shared autowired service.
     *
     * @return \App\Controller\HomeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/DashboardControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractDashboardController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/HomeController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/HomeService.php';

        $container->services['App\\Controller\\HomeController'] = $instance = new \App\Controller\HomeController(($container->privates['App\\Service\\HomeService'] ??= new \App\Service\HomeService()));

        $instance->setContainer(($container->privates['.service_locator.yTMp7CA'] ?? $container->load('get_ServiceLocator_YTMp7CAService'))->withContext('App\\Controller\\HomeController', $container));

        return $instance;
    }
}
