<?php

namespace ContainerUiptYz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotVerifiedEmailControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\NotVerifiedEmailController' shared autowired service.
     *
     * @return \App\Controller\NotVerifiedEmailController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/NotVerifiedEmailController.php';

        $container->services['App\\Controller\\NotVerifiedEmailController'] = $instance = new \App\Controller\NotVerifiedEmailController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\NotVerifiedEmailController', $container));

        return $instance;
    }
}
