<?php

namespace ContainerUiptYz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeliculasSeriesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PeliculasSeriesController' shared autowired service.
     *
     * @return \App\Controller\PeliculasSeriesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PeliculasSeriesController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/HomeService.php';

        $container->services['App\\Controller\\PeliculasSeriesController'] = $instance = new \App\Controller\PeliculasSeriesController(($container->privates['App\\Service\\HomeService'] ??= new \App\Service\HomeService()));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\PeliculasSeriesController', $container));

        return $instance;
    }
}
