<?php

namespace ContainerIgYaWsu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhook_ControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'webhook.controller' shared service.
     *
     * @return \Symfony\Component\Webhook\Controller\WebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webhook/Controller/WebhookController.php';

        return $container->services['webhook.controller'] = new \Symfony\Component\Webhook\Controller\WebhookController([], ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)));
    }
}
