<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ljGTLw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ljGTLw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8ljGTLw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8ljGTLw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8ljGTLw\App_KernelDevDebugContainer([
    'container.build_hash' => '8ljGTLw',
    'container.build_id' => '44f66a32',
    'container.build_time' => 1714931547,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ljGTLw');
